name: etrack  # Replace 'etrack' with your desired project name

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  pdf: ^3.10.4
  printing: ^5.12.0
  animations: ^2.0.7
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0

environment:
  sdk: '^3.7.0'